### PR TITLE
Test property examples branch

### PR DESCRIPTION
**Pull request by bpaul4**
## Fixes # .
Addresses some minor typos in #9

## Proposed changes:
- Fixing typos in physical/reaction property package example notebook

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by andrewlee94** [comment]
@bpaul4 This PR seems to gave gotten messed up when I updated my branch and pushed some new changes. Would you be able to point out the specific typos you found instead?

**Review by andrewlee94 — CHANGES_REQUESTED** [review]
This seems to be making significant changes to the Jupyter notebook files (or at least Github thinks it is).

**Comment by bpaul4** [comment]
Sure, I can do that. In the Physical Property Package tutorial, under the 'Components of a Property Package' section one of the lines had "the the State Block" and I removed one of the 'the''s; under 'Step 6' in the last paragraph I changed "which required temperature and pressure" to "which requires temperature and pressure." Not sure why it saw so many other changes.

**Comment by andrewlee94** [comment]
At least part of the reason is because I cleared all the execution of cells from my version, whereas your I think still has executed cells.

**Comment by bpaul4** [comment]
Going forwards, would it be best to clear executed cells before attempting to merge? I believe some of the IDAES examples did have executed cells (output showing) when first installed and before running.

**Comment by andrewlee94** [comment]
It depends on the notebook.

**Comment by bpaul4** [comment]
Alright, thank you @andrewlee94  for your advice/fix and please let me know if I may make this process smoother in future PRs. I believe all the authentication issues have been addressed on my end, so access (where appropriate) should not be an issue going forwards.

**Pull request closed without merging**
